INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Consulta de planejamento financeiro', '10/12/2024', 'Campinas - SP');
INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Encontro com amigos', '25/12/2024', 'Sorocaba - SP');
INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Aula de inglês', '17/12/2024', 'Online');
INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Treinamento na academia', '24/12/2024', 'Itu - SP');
INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Palestra sobre tecnologia', '15/12/2024', 'São Paulo - SP');
INSERT INTO AGENDA (DESCRIPTION, DURATION, LOCAL) VALUES ('Sessão de terapia', '30/11/2024', 'Jundiaí - SP');
